DesignStudio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.conf import settings
from .views import RegisterView, CustomLogoutView, SuccessView, AccountListView, login_user
from .views import CreateApplicationView
from .views import IndexView
from django.conf.urls.static import static
from .views import ApplicationDeleteView
from django.urls import path
from .views import AllAppsListView, EditApp, AllCategoriesListView, EditCategory, CategoryDelete, CreateCategory, AllUsersListView, UserDeleteView, UserEditView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная страница
    path('success/', SuccessView.as_view(), name='success'),
    path('register/', RegisterView.as_view(), name='register'),  # Маршрут для регистрации
    path('login/', login_user, name='login'),  # URL для страницы входа
    path('logout/', CustomLogoutView.as_view(), name='logout'),  # URL для выхода
    path('create_application/', CreateApplicationView.as_view(), name='create_application'),
    path('all-apps/', AllAppsListView.as_view(), name='all_apps'),
    path('all-categories/', AllCategoriesListView.as_view(), name='all_categories'),
    path('personal_account/', AccountListView.as_view(), name='personal_account'),
    path('application/delete_application/<int:pk>/', ApplicationDeleteView.as_view(), name='delete_application'),
    path('app/<int:pk>/edit/', EditApp.as_view(), name='edit_app'),
    path('category/<int:pk>/edit/', EditCategory.as_view(), name='edit_category'),
    path('category/delete/<int:pk>/', CategoryDelete.as_view(), name='delete_category'),
    path('category/create/', CreateCategory.as_view(), name='create_category'),
    path('all-users/', AllUsersListView.as_view(), name='all_users'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
    path('user/edit/<int:pk>/', UserEditView.as_view(), name='edit_user'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=200, verbose_name='Имя пользователя', unique=True)
    first_name = models.CharField(max_length=200, verbose_name='Имя')
    last_name = models.CharField(max_length=200, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=200, verbose_name='Отчество')
    email = models.EmailField(max_length=200, verbose_name='Email', unique=True)
    password = models.CharField(max_length=200, verbose_name='Пароль')
    is_approved = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Application(models.Model):
    STATUS_CHOICES = [
        ('new', 'Новая'),
        ('work', 'Принято в работу'),
        ('done', 'Выполнено'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos/', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='new')
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # Add this line

    def __str__(self):
        return self.title

    def time_created_f(self):
        return self.created_at

    def get_category(self):
        categories = self.category.all()[:1]
        return ', '.join(str(category.title) for category in categories)

catalog/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
import re
from .models import Application

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control'}),  # Добавляем класс Bootstrap
        error_messages={
            'required': 'Email обязателен для заполнения.',
            'invalid': 'Введите корректный email адрес.'
        }
    )

    full_name = forms.CharField(
        label='ФИО',
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),  # Добавляем класс Bootstrap
        error_messages={
            'required': 'ФИО обязательно для заполнения.'
        }
    )

    username = forms.CharField(
        label='Логин',
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),  # Добавляем класс Bootstrap
        error_messages={
            'required': 'Логин обязателен для заполнения.'
        }
    )

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),  # Добавляем класс Bootstrap
        required=True
    )

    password2 = forms.CharField(
        label='Повтор пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),  # Добавляем класс Bootstrap
        required=True
    )

    consent = forms.BooleanField(
        label='Согласие на обработку персональных данных',
        required=True,
        error_messages={
            'required': 'Необходимо согласие на обработку персональных данных.'
        }
    )

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'password1', 'password2', 'consent']

    def clean_full_name(self):
        full_name = self.cleaned_data['full_name']
        if not re.match(r'^[А-Яа-яЁё\s\-]+$', full_name):
            raise ValidationError('ФИО должно содержать только кириллические буквы, пробелы и дефисы.')
        return full_name

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.match(r'^[a-zA-Z0-9\-]+$', username):
            raise ValidationError('Логин должен содержать только латиницу, цифры и дефисы.')

        # Проверка уникальности логина
        if User.objects.filter(username=username).exists():
            raise ValidationError('Этот логин уже занят.')

        return username

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают.")

class LoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=200, label='', widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя'}))
    password = forms.CharField(required=True, max_length=200, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['title', 'description', 'category', 'photo']

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo.size > 2 * 1024 * 1024:  # Проверка на максимальный размер 2 Мб
            raise forms.ValidationError("Размер файла не должен превышать 2 Мб.")
        return photo

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        application = super().save(commit=False)
        if self.user:
            application.creator = self.user

        if commit:
            application.save()
            self.save_m2m()
        return application

class CaptchaForm(forms.Form):
    captcha_answer = forms.IntegerField(label='2 + 2 * 2 = ')

    def clean_captcha_answer(self):
        answer = self.cleaned_data.get('captcha_answer')
        if answer != 6:  # Проверка правильного ответа
            raise ValidationError("Неправильный ответ на капчу. Попробуйте снова.")
        return answer

class EditAppForm(forms.ModelForm):
    design_comment = forms.CharField(required=False, max_length=200, label='', widget=forms.Textarea(attrs={'placeholder': 'Комментарий'}))
    design_photo = forms.FileField(required=False, label='Изображение дизайна', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])])

    class Meta:
        model = Application
        fields = ['category', 'status', 'design_comment', 'design_photo']

    def clean_design_comment(self):
        new_status = self.cleaned_data.get('status')
        design_comment = self.cleaned_data.get('design_comment')
        if new_status == 'work' and not design_comment:
            raise ValidationError('Комментарий должен быть заполнен.')
        return design_comment

    def clean_design_photo(self):
        new_status = self.cleaned_data.get('status')
        design_photo = self.cleaned_data.get('design_photo')
        if new_status == 'done' and not design_photo:
            raise ValidationError('Изображение должно быть заполнено.')
        return design_photo

class AppFilterForm(forms.Form):
    STATUS_CHOICES = [
        ('', 'Все'),
        ('new', 'Новая'),
        ('work', 'Принято в работу'),
        ('done', 'Выполнено'),
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, label='Статус')

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['is_staff', 'is_superuser', 'is_approved']

catalog/templates/catalog/all_categories.html
{% extends "basic.html" %}

{% block content %}

<h3>Категории</h3>
    <a href="{% url 'create_category' %}" class="btn btn-primary mb-3">Создать категорию</a>
    {% if category_list %}
        <hr>
        {% for category in category_list %}
            <a href="{% url 'edit_category' category.id %}" class="h5 d-block mb-3">{{ category }}</a>
        {% endfor %}
    {% else %}
      <p>В базе данных нет категорий</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/all_users.html
{% extends "basic.html" %}

{% block content %}

<h3>Пользователи</h3>
    {% if user_list %}
        <hr>
        {% for user in user_list %}
            <a href="{% url 'edit_user' user.id %}" class="h5 d-block mb-3">{{ user }}</a>
        {% endfor %}
    {% else %}
      <p>В базе данных нет пользователей</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/create_application.html
{% extends "basic.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2>Создать новую заявку</h2>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Отправить заявку</button>
        </div>
    </form>
    {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field, errors in form.errors.items %}
                    <li><strong>{{ field.label }}:</strong> {{ errors }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/create_category.html
{% extends "basic.html" %}

{% block content %}

<h3>Создание категории</h3>
<form method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary font-weight-bold">Создать</button>
</form>

{% endblock %}

catalog/templates/catalog/delete_application.html
{% extends "basic.html" %}

{% block content %}
  <h1>Удалить заявку</h1>

  <p class="h5">Вы точно хотите удалить заявку: {{ object }}?</p>

  <div class="app-display-card app-display-card-index">
      <div>
          <p class="mb-2 h5 text-center">{{ object.title }}</p>
          <p class="text-secondary mt-1 mb-1">{{ object.time_created_f }}</p>
          <p class="text-white mb-1 app-display-category text-truncate">{{ object.get_category }}</p>
      </div>
      {% if object.photo %}
          <img src="{{ object.photo.url }}" alt="{{ object.title }}" class="app-display-img app-display-img-index"/>
      {% endif %}
  </div>

  <form action="" method="POST" class="mt-3">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'personal_account' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

catalog/templates/catalog/delete_category.html
{% extends "basic.html" %}

{% block content %}
  <h1>Удалить заявку</h1>

  <p class="h5">Вы точно хотите удалить категорию: {{ category }}?</p>

  <form action="" method="POST" class="mt-3">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger font-weight-bold">Удалить</button>
    <a href="{% url 'all_categories' %}" class="btn btn-secondary font-weight-bold">Отмена</a>
  </form>
{% endblock %}

catalog/templates/catalog/delete_confirmation.html
{% extends "basic.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container mt-5">
    <h2>Подтвердите удаление заявки</h2>
    <p>Вы уверены, что хотите удалить заявку: <strong>{{ application.title }}</strong>?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/delete_user.html
{% extends "basic.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Подтвердите удаление пользователя</h2>
    <p>Вы уверены, что хотите удалить пользователя <strong>{{ user.get_username }}</strong> со статусом: <strong>{{ status }}</strong>?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'all_users' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/edit_app.html
{% extends "basic.html" %}

{% block content %}

    <h3>Редактирование заявки</h3>
    <div class="app-display-card app-display-card-edit">
        <div>
            <p class="mb-2 h5 text-center">{{ object.title }}</p>
            <p class="text-secondary mt-1 mb-1">{{ object.time_created_f }}</p>
            <p class="text-white mb-1 app-display-category text-truncate">{{ object.get_categories }}</p>
        </div>
        <div>
            {% if object.photo %}
                <img src="{{ object.photo.url }}" alt="{{ object.title }}" class="app-display-img"/>
            {% endif %}
            <p>{{ object.get_status_display }}</p>
        </div>
    </div>
    <form method="post" novalidate enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary font-weight-bold mb-5">Сохранить</button>
    </form>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const optionField = document.getElementById('id_status');
            const commentField = document.querySelector('p:has(#id_design_comment)');
            const photoField = document.querySelector('p:has(#id_design_photo)');
            const discountField = document.querySelector('p:has(#id_discount)');

            function toggleAdditionalFields() {
                if (optionField.value === "work") {
                    commentField.style.display = "block";
                    photoField.style.display = "none";
                    discountField.style.display = "none";
                }
                else if (optionField.value === "done") {
                    photoField.style.display = "block";
                    commentField.style.display = "none";
                    discountField.style.display = "block";
                }
                else {
                    discountField.style.display = "none";
                    commentField.style.display = "none";
                    photoField.style.display = "none";
                }

                console.log(optionField.value)
            }

            toggleAdditionalFields();
            optionField.addEventListener("change", toggleAdditionalFields);
        });
    </script>
{% endblock %}

catalog/templates/catalog/edit_category.html
{% extends "basic.html" %}

{% block content %}

    <h3>Редактирование категории</h3>
    <form method="post" novalidate enctype="multipart/form-data" class="mt-1">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary font-weight-bold">Сохранить</button>
        <a href="{% url 'delete_category' object.id %}" class="btn btn-danger font-weight-bold">Удалить</a>
    </form>
{% endblock %}

catalog/templates/catalog/edit_user.html
{% extends "basic.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Редактировать пользователя: {{ user.username }}</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Отображаем поля формы -->
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'delete_user' object.id %}" class="btn btn-danger font-weight-bold">Удалить</a>
        <a href="{% url 'all_users' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/personal_account.html
{% extends "basic.html" %}

{% block content %}

<h3>Личный кабинет</h3>
    {% if designapplication_list %}
        <div class="container">
            <div class="row">
                {% for application in designapplication_list %}
                    <div class="col-md-4 mb-4">  <!-- Блок для каждой заявки -->
                        <div class="card"> <!-- Убираем фиксированную высоту блока -->
                            {% if application.photo %}
                                <img src="{{ application.photo.url }}" alt="{{ application.title }}" class="card-img-top" style="max-height: 200px; object-fit: cover;">
                            {% endif %}
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">
                                    <a href="{{ application.get_absolute_url }}">{{ application.title }}</a>
                                </h5>
                                <p class="card-text">
                                    <strong>Дата:</strong> {{ application.created_at|date:"d.m.Y H:i" }}<br>
                                    <strong>Категория:</strong> {{ application.category }}<br>
                                </p>
                                <details style="margin-top: auto;">
                                    <summary style="cursor: pointer; color: #007bff; padding: 0; margin: 0;">
                                        Показать описание
                                    </summary>
                                    <p style="margin-top: 10px; margin-bottom: 0;">{{ application.description }}</p>
                                </details>
                                {% if application.status == 'new' %}
                                    <a href="{% url 'delete_application' application.id %}" class="button delete-button pt-2 pb-2">Удалить</a>
                                {% else %}
                                    <p class="button delete-button-inactive pt-2 pb-2 mb-0">В работе</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>У вас нет заявок</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/success.html
{% extends "basic.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="alert alert-success" role="alert">
            <h1>Заявка успешно создана!</h1>
            <p>Спасибо за вашу заявку. Мы свяжемся с вами в ближайшее время.</p>
        </div>
        <div class="mt-3">
            <a href="{% url 'index' %}" class="btn btn-primary">Создать новую заявку</a>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/success_captcha.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Успех</title>
</head>
<body>
    <h1>Форма успешно отправлена!</h1>
    <p>Спасибо за ваше сообщение.</p>
</body>
</html>